### ISSUE TITLE
Change the sequencer registration command to improve ergonomics

### ISSUE THREAD

**Issue by artemijspavlovs** [dymensionxyz/dymension#1035]
Sequencer metadata is optional when creating a sequencer but the positional argument forces the user to provide it. 

```
dymd tx sequencer create-sequencer [pubkey] [rollapp-id] [metadata] [bond]
```

Ideally, it should be last in positional argument list 

```
dymd tx sequencer create-sequencer [pubkey] [rollapp-id] [bond] [metadata]
```

and be ignored if it's not provided (filled with empty values like it does now when the json file contains an empty json object):

```
// sequencer-metadata.json
{}
```

```
// tx

...
    metadata:
      contact_details: null
      details: ""
      evm_rpcs: []
      explorer_url: ""
      extra_data: null
      gas_price: null
      genesis_urls: []
      moniker: ""
      p2p_seeds: []
      rest_api_urls: []
      rpcs: []
      snapshots: []
    rollapp_id: art_2000-1
  non_critical_extension_options: []
  timeout_height: "0"
...
```
