### ISSUE TITLE
GUI fixes

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1094]
we need the following changes:
add display_name to the rollapp metadata (updatable at any time by rollapp owner like other metadata fields)
when showing a rollapp (dymd q rollapp show) -> we don’t return all the rollapp object (e.g alias etc)
when listing all rollapps, we need to return their details. currently it returns:

```
- latestFinalizedStateIndex:
    index: "23403"
    rollappId: rollappy_700002-1
  latestStateIndex:
    index: "23403"
    rollappId: rollappy_700002-1
  rollappId: rollappy_700002-1
should look something like:
- latestFinalizedStateIndex:
    index: "23403"
    rollappId: rollappy_700002-1
  latestStateIndex:
    index: "23403"
    rollappId: rollappy_700002-1
  rollappId: rollappy_700002-1
  <other-rollapp-fields>
```

where it’s best currently not to change the api (just enhance it with more data) to not hurt any clients using it.

list all show the same for each one as show does for one
