### ISSUE TITLE
Request change: IRO contract name

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymension#1506]
```yaml
- base: IRO/mcfourthfee_10019-1
  denom_units:
  - aliases: []
    denom: IRO/mcfourthfee_10019-1
    exponent: 0
  - aliases: []
    denom: IRO/MCFOURTH
    exponent: 18
  description: Future token for rollapp mcfourthfee_10019-1
  display: IRO/MCFOURTH
  name: IRO/mcfourthfee_10019-1 // <=
  symbol: IRO/MCFOURTH
  uri: ""
  uri_hash: ""
```
Name should be the same as Display and Symbol
