### ISSUE TITLE
Data Correction Request: denom metadata of existing GAMM on mainnet

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymension#1631]
The existing GAMM pools on mainnet, have denom metadata not satisfy validate basic (already fixed in 3D), so please correct them during migration.

**Comment by mtsitrin** [comment]
old metadata:
```
dymd --node https://rpc-dym-migration-test-2.mzonder.com:443 q bank denom-metadata --denom gamm/pool/13
metadata:
  base: gamm/pool/13
  denom_units:
  - aliases:
    - attopoolshare
    denom: gamm/pool/13
    exponent: 0
  - aliases: []
    denom: GAMM-13
    exponent: 18
  description: The share token of the gamm pool 13
  display: GAMM-13
  name: ""
  symbol: ""
  uri: ""
  uri_hash: ""
  ```
  
  new (fixed) metadata:
  ```
  dymd --node https://rpc-dym-migration-test-2.mzonder.com:443 q bank denom-metadata --denom gamm/pool/14
metadata:
  base: gamm/pool/14
  denom_units:
  - aliases:
    - attopoolshare
    denom: gamm/pool/14
    exponent: 0
  - aliases: []
    denom: GAMM-14
    exponent: 18
  description: The share token of the gamm pool 14
  display: GAMM-14
  name: gamm/pool/14
  symbol: GAMM-14
  uri: ""
  uri_hash: ""
  ```
  
  missing display and name for old pools
  @VictorTrustyDev correct?
